//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paxstore.OpenApi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paxstore.OpenApi.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantCategoryBatchCreateRequest cannot be null and empty! 的本地化字符串。
        /// </summary>
        internal static string merchantCategoryBatchCreateRequestInvalid {
            get {
                return ResourceManager.GetString("merchantCategoryBatchCreateRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantCategoryCreateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string merchantCategoryCreateRequestIsNull {
            get {
                return ResourceManager.GetString("merchantCategoryCreateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantCategoryId cannot be null and cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string merchantCategoryIdInvalid {
            get {
                return ResourceManager.GetString("merchantCategoryIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All the category names in the list cannot be blank! 的本地化字符串。
        /// </summary>
        internal static string merchantCategoryNameEmpty {
            get {
                return ResourceManager.GetString("merchantCategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantCategoryUpdateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string merchantCategoryUpdateRequestIsNull {
            get {
                return ResourceManager.GetString("merchantCategoryUpdateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter resellerCreateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string merchantCreateRequestIsNull {
            get {
                return ResourceManager.GetString("merchantCreateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant category name &apos;[NAME]&apos; is too long! 的本地化字符串。
        /// </summary>
        internal static string merchanteCategoryNameTooLong {
            get {
                return ResourceManager.GetString("merchanteCategoryNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant category remarks &apos;[REMARKS]&apos; is too long! 的本地化字符串。
        /// </summary>
        internal static string merchanteCategoryRemarksTooLong {
            get {
                return ResourceManager.GetString("merchanteCategoryRemarksTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantUpdateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string merchantUpdateRequestIsNull {
            get {
                return ResourceManager.GetString("merchantUpdateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknow SDK request error! 的本地化字符串。
        /// </summary>
        internal static string msg_16000 {
            get {
                return ResourceManager.GetString("msg_16000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection timeout! 的本地化字符串。
        /// </summary>
        internal static string msg_16104 {
            get {
                return ResourceManager.GetString("msg_16104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaseUrl not correct! 的本地化字符串。
        /// </summary>
        internal static string msg_16111 {
            get {
                return ResourceManager.GetString("msg_16111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter packageName is mandatory! 的本地化字符串。
        /// </summary>
        internal static string packageNameMandatory {
            get {
                return ResourceManager.GetString("packageNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parameters and base64FileParameters cannot be null at same time! 的本地化字符串。
        /// </summary>
        internal static string paramAndFileParamEmptySameTime {
            get {
                return ResourceManager.GetString("paramAndFileParamEmptySameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter createApkParameterRequest is mandatory! 的本地化字符串。
        /// </summary>
        internal static string paramCreateApkParameterRequestMandatory {
            get {
                return ResourceManager.GetString("paramCreateApkParameterRequestMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter apkParameterId cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string parameterApkParameterIdIsInvalid {
            get {
                return ResourceManager.GetString("parameterApkParameterIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter attributeId cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string parameterAttributeIdInvalid {
            get {
                return ResourceManager.GetString("parameterAttributeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter batchDeletionRequest is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterBatchDeletionRequestMandatory {
            get {
                return ResourceManager.GetString("parameterBatchDeletionRequestMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter createTerminalApkRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string parameterCreateTerminalApkRequestNull {
            get {
                return ResourceManager.GetString("parameterCreateTerminalApkRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property SerialNo and TID in createTerminalApkRequest cannot be blank at same time! 的本地化字符串。
        /// </summary>
        internal static string parameterCreateTerminalApkRequestSnTidEmpty {
            get {
                return ResourceManager.GetString("parameterCreateTerminalApkRequestSnTidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The max size of template names is 10! 的本地化字符串。
        /// </summary>
        internal static string parameterCreateTerminalApkRequestTemplateNameTooLong {
            get {
                return ResourceManager.GetString("parameterCreateTerminalApkRequestTemplateNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter firmwareName is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterFirmwareNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("parameterFirmwareNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter merchantId cannot be null and cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string parameterMerchantIdInvalid {
            get {
                return ResourceManager.GetString("parameterMerchantIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter packageName is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterPackageNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("parameterPackageNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter pushFirmware2TerminalRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string parameterPushFirmware2TerminalRequestNull {
            get {
                return ResourceManager.GetString("parameterPushFirmware2TerminalRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property SerialNo and TID in pushFirmware2TerminalRequest cannot be blank at same time! 的本地化字符串。
        /// </summary>
        internal static string parameterpushFirmware2TerminalRequestSnTidEmpty {
            get {
                return ResourceManager.GetString("parameterpushFirmware2TerminalRequestSnTidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter pushRki2TerminalRequest is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterPushRki2TerminalRequestNull {
            get {
                return ResourceManager.GetString("parameterPushRki2TerminalRequestNull", resourceCulture);
			}
		}
		
        ///   查找类似 Serial number is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterSerialNoMandatory {
            get {
                return ResourceManager.GetString("parameterSerialNoMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter serialNo is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterSnCannotBeEmpty {
            get {
                return ResourceManager.GetString("parameterSnCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalParameterVariableCreateReques is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterTerminalParameterVariableCreateRequestMandatory {
            get {
                return ResourceManager.GetString("parameterTerminalParameterVariableCreateRequestMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalTid cannot be blank! 的本地化字符串。
        /// </summary>
        internal static string parameterTerminalTidEmpty {
            get {
                return ResourceManager.GetString("parameterTerminalTidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalVariableId cannot be null and cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string parameterTerminalVariableIdInvalid {
            get {
                return ResourceManager.GetString("parameterTerminalVariableIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalVariableUpdateRequest is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterTerminalVariableUpdateRequestMandatory {
            get {
                return ResourceManager.GetString("parameterTerminalVariableUpdateRequestMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter tid is mandatory! 的本地化字符串。
        /// </summary>
        internal static string parameterTidCannotBeEmpty {
            get {
                return ResourceManager.GetString("parameterTidCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter updateApkParameterRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string parameterUpdateApkParameterRequestIsNull {
            get {
                return ResourceManager.GetString("parameterUpdateApkParameterRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter apkParameterId cannot be null and be less than 1! 的本地化字符串。
        /// </summary>
        internal static string paramterApkParameterIdIsNull {
            get {
                return ResourceManager.GetString("paramterApkParameterIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter resellerCreateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string resellerCreateRequestIsNull {
            get {
                return ResourceManager.GetString("resellerCreateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter resellerId cannot be null and cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string resellerIdInvalid {
            get {
                return ResourceManager.GetString("resellerIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter resellerUpdateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string resellerUpdateRequestIsNull {
            get {
                return ResourceManager.GetString("resellerUpdateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rkikey is mandatory! 的本地化字符串。
        /// </summary>
        internal static string rkiKeyMandatory {
            get {
                return ResourceManager.GetString("rkiKeyMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerialNo or Tid is mandatory! 的本地化字符串。
        /// </summary>
        internal static string snTidMandatory {
            get {
                return ResourceManager.GetString("snTidMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalCreateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string terminalCreateRequestIsNull {
            get {
                return ResourceManager.GetString("terminalCreateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalId cannot be null and cannot be less than 1! 的本地化字符串。
        /// </summary>
        internal static string terminalIdInvalid {
            get {
                return ResourceManager.GetString("terminalIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalUpdateRequest cannot be null! 的本地化字符串。
        /// </summary>
        internal static string terminalUpdateRequestIsNull {
            get {
                return ResourceManager.GetString("terminalUpdateRequestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter terminalVariableId invalid! 的本地化字符串。
        /// </summary>
        internal static string terminalVariableIdInvalid {
            get {
                return ResourceManager.GetString("terminalVariableIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter serialNo and tid  cannot be blank at same time! 的本地化字符串。
        /// </summary>
        internal static string tidAndSnIsMandatory {
            get {
                return ResourceManager.GetString("tidAndSnIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VariableIds cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string variableIdsMandatory {
            get {
                return ResourceManager.GetString("variableIdsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variableList can not be empty 的本地化字符串。
        /// </summary>
        internal static string variableListMandatory {
            get {
                return ResourceManager.GetString("variableListMandatory", resourceCulture);
            }
        }
    }
}
